development:
  adapter: mysql2
  database: GEM_TEST_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: GEM_TEST_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: GEM_TEST_production
  username: root
  password: 
  encoding: utf8